# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- bash: |
    set -euo pipefail
    curl -s --location --output file.txt 'https://api.open-meteo.com/v1/forecast?latitude=12.97&longitude=77.59&daily=temperature_2m_max%2Ctemperature_2m_min%2Cprecipitation_probability_mean&timezone=Asia%2FKolkata'
    head -n 20 file.txt
    displayName: 'Run a multi-line script'
