

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    curl -sL 'https://jsonplaceholder.typicode.com/todos/1' | tee file.txt
    echo file.txt
    cat file.txt
  displayName: 'Run a multi-line script'
